from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from fastapi.middleware.cors import CORSMiddleware
from typing import Optional
import time

from services.prompt_builder import build_prompt
from services.marks_scaler import scale_response

app = FastAPI()

# Enable CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # For development, allow all origins
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class AssignmentRequest(BaseModel):
    question: str
    subject: str
    marks: int

class AssignmentResponse(BaseModel):
    structured_answer: str

def mock_llm_call(prompt: str) -> str:
    """
    Placeholder function for LLM call.
    Simulates processing time and returns a structured response.
    """
    time.sleep(2)  # Simulate API latency
    return f"""
# Generated Answer

Based on your input, here is a structured response:

{prompt}

**Key Concepts:**
- Concept 1: Relevant to the question.
- Concept 2: Another key point.

**Detailed Explanation:**
This is a placeholder for the detailed explanation generated by the LLM. It would expand on the key concepts mentioned above.

**Conclusion:**
A brief summary of the answer.
"""

@app.post("/generate", response_model=AssignmentResponse)
async def generate_assignment(request: AssignmentRequest):
    try:
        # Build the prompt based on subject and marks
        prompt = build_prompt(request.question, request.subject, request.marks)
        
        # Call the mock LLM
        raw_response = mock_llm_call(prompt)
        
        # Scale the response based on marks (optional post-processing)
        scaled_response = scale_response(raw_response, request.marks)
        
        return AssignmentResponse(structured_answer=scaled_response)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/")
async def root():
    return {"message": "Engineering Assignment Accelerator API is running"}
